#app
server:
    port: 8010

spring:
  application:
    name: microservice-simple-consumer-movie
    
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://yp:whiletrue@localhost:8761/eureka/
  instance:
    prefer-ip-address: true